name = "twin"
compatibility_date = "2024-10-18"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

# Assets directory for static files
[assets]
directory = ".open-next/assets"

# Public environment variables (non-sensitive)
[vars]
NEXT_PUBLIC_APP_URL = "https://twin.erniesg.workers.dev"

# Secrets (set via: wrangler secret put <KEY_NAME>)
# - NEXT_PUBLIC_SUPABASE_URL
# - NEXT_PUBLIC_SUPABASE_ANON_KEY