name = "twin"
compatibility_date = "2024-10-18"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

# Assets directory for static files
[assets]
directory = ".open-next/assets"

# Environment variables
[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://lbyicktafbnqwbieffbj.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxieWlja3RhZmJucXdiaWVmZmJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3NjQyNDAsImV4cCI6MjA3NjM0MDI0MH0.CXNC9UmCRe7707k4pnO4C992hcC3gNmQq41DPcKdaio"
NEXT_PUBLIC_APP_URL = "https://twin.erniesg.workers.dev"