name = "twin-api"
main = "src/index.ts"
compatibility_date = "2025-01-18"

# Development environment
[env.development]
workers_dev = true

[env.development.vars]
SUPABASE_URL = "http://localhost:54321"
SUPABASE_SERVICE_KEY = "dev-key"

# Production environment
[env.production]
workers_dev = false
routes = [
  { pattern = "api.twin.ai/*", zone_name = "twin.ai" }
]

[env.production.vars]
# These will be set via wrangler secret put
# SUPABASE_URL = "set-via-secret"
# SUPABASE_SERVICE_KEY = "set-via-secret"
# MEM0_API_KEY = "set-via-secret"
# OPENAI_API_KEY = "set-via-secret"
# ANTHROPIC_API_KEY = "set-via-secret"
# GOOGLE_AI_KEY = "set-via-secret"

# Performance settings
[limits]
cpu_ms = 50

[placement]
mode = "smart"

# Observability
[observability]
enabled = true

# Build configuration
[build]
command = "npm run build"

[build.upload]
format = "modules"
main = "./src/index.ts"