name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main  # Automatically deploy when pushing to main
  workflow_dispatch:  # Allow manual triggers

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build Next.js application
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_APP_URL: https://twin.erniesg.workers.dev
          NEXT_PUBLIC_USE_MOCK: false
          NEXT_PUBLIC_MCP_SERVER_URL: https://twin-mcp-persona.erniesg.workers.dev/mcp
        run: pnpm build

      - name: Build for Cloudflare
        run: echo "n" | npx @opennextjs/cloudflare build || npx @opennextjs/cloudflare build --skip-prompts || npx @opennextjs/cloudflare build

      - name: Deploy to Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: npx @opennextjs/cloudflare deploy

      - name: Deploy MCP Persona Worker
        working-directory: ./workers/mcp-persona
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: npx wrangler deploy

      - name: Deployment notification
        if: success()
        run: |
          echo "✅ Successfully deployed to https://twin.erniesg.workers.dev"
          echo "✅ MCP Worker deployed to https://twin-mcp-persona.erniesg.workers.dev"
          echo "Version: ${{ github.sha }}"
